version: '3'

services:
  # Backend Node.js with TypeScript
  backend:
    image: node:14
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development
    command: ["npm", "run", "dev"]
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  # Frontend React
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    depends_on:
      - backend
